language: ruby
rvm:
  - 2.2.2

env:
  - RAILS_VERSION=3.2
  - RAILS_VERSION=4.2
  - RAILS_VERSION=5.0
  - RAILS_VERSION=5.1

deploy:
  provider: rubygems
  api_key: ${RUBYGEMS_API_KEY}
  on:
    tags: true
